name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and deploy
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup MSBuild path
      uses: microsoft/setup-msbuild@v1.1
      with:
        vs-version: "[17.1.5)"
    
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
    
    - name: Build
      run: msbuild Server\Server.csproj -t:rebuild -verbosity:diag -property:Configuration=Release
