name: Build and Deploy

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

on:
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'
      - '.idea/*'
      - '.vs/*'

concurrency: 
  group: "build-and-release"
  cancel-in-progress: true

jobs:
  build:
    name: Build and deploy
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'
    
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
    
    - name: Build
      run: dotnet publish -c=Release

    - name: Publish the build
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Automatic Build"
        files: |
          Server\bin\Release\net35\ServerEmulator.dll
